### ISSUE TITLE
Error when running terraform plan

### ISSUE THREAD

**Issue by chasezheng** [WOGRA-AG/terraform-kustomization-kubeflow#1]
After the initial creation, I get an error with subsequent "terraform plan"
```
Error: Invalid for_each argument
  on ../../../../terraform-kustomization-kubeflow/terraform_module/cert-manager.tf line 6, in resource "kustomization_resource" "cert-manager-base":
   6:   for_each = data.kustomization_build.cert-manager-base.ids
    ├────────────────
    │ data.kustomization_build.cert-manager-base.ids is a set of string, known only after apply
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
It has to do with "kustomization_build". Any way to work around this issue?

**Comment by chasezheng** [comment]
this line might be the cause for the error:
https://github.com/kbst/terraform-provider-kustomization/blob/master/kustomize/data_source_kustomization_build.go#L43
could try to set it to false.

This is what computed=true means: https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#computed

**Comment by chasezheng** [comment]
*didn't mean to close this.

**Comment by pd-t** [comment]
Hi  chase,
thanks for your Bug report. We will have a look on it. Can you provide us details which version you used? What kind of kubernetes did you use?
Best
Thomas

**Comment by chasezheng** [comment]
Hi I was using
GKE 1.21
terraform 1.1.9 
hashicorp/google/4.22.0
hashicorp/kubernetes/2.11.0
kbst/kustomization/0.8.0
gavinbunney/kubectl/1.14.0
And this module, 0.3.0

**Comment by pd-t** [comment]
Did you used a tagged version of the module or the latest. If it was the latest, which commit sha?

**Comment by pd-t** [comment]
Ah, ok I see you used the version 0.3.0. Yes, there can be an issue with this version. Currently, I review the code and test the latest version with k3d. If you can wait till tomorrow I will tag a new version. We realized two more things in internal testing which will get fixed by tomorrow.

**Comment by pd-t** [comment]
Ok, so I finished the release. Please try again with module version 0.3.2. it works fine using the k3s image mentioned in the readme on my x86. Please inform me in case it is not working (you can reopen the issue). GKE should be fine. We are also using it on GKE.
